language: node_js
node_js:
  - '12'

cache:
  directories:
    - node_modules

install:
  - npm install -g pnpm
  - pnpm install

deploy:
  provider: npm
  api_token: $NPM_API_TOKEN
  on:
    tags: true
  edge: true
